server:  
  port: ${PORT:8889}
    
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qith/sample-spring-cloud-config-repo
          username: ${github.username}
          password: ${github.password}
          cloneOnStart: true