spring:  
  application:
    name: discovery-service

server:  
  port: ${PORT:8761}
      
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000